### ISSUE TITLE
First Skeleton for front end

### ISSUE THREAD

**Issue by Cademcp** [CSIS-BU/cis445-project1-tannercadematt#5]

**Comment by djlin** [comment]
I would recommend putting some descriptions to your issues so it'd be easier for others to follow.

**Comment by Cademcp** [comment]
This first skeleton is going to be the baseline/testing front end. It will be used to practice connecting the python API to the front end, and dynamically generating elements in HTML via Python

**Comment by djlin** [comment]
Looks good to me 👍
